[tool.poetry]
name = "erp-cicero"
version = "0.1.0"
description = ""
authors = ["Marcuth <me@marcuth.dev>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
ttkbootstrap = "^1.14.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
